"use client"
import { ArrowLeft, FileText, Images, MessageSquare, Plus, Save, Sparkles, Trash2 } from "lucide-react"
import { useParams, useRouter } from "next/navigation"
import { useEffect, useState } from "react"
import { Button } from "@/components/ui/button"
import { ProjectSummaryTools } from "@/components/project-summary-tools"
import type { DiagramPlan, DiagramPlanItem, Project, ProjectChatMessage, ProjectChatSession, ProjectDiagram } from "@/lib/project-types"

type Tab="summary"|"chat"|"plan"|"diagrams"
export default function ProjectDetailPage(){
 const p=useParams<{lang:string;id:string}>(),router=useRouter()
 const [project,setProject]=useState<Project|null>(null),[tab,setTab]=useState<Tab>("summary"),[summary,setSummary]=useState(""),[saved,setSaved]=useState(false)
 const [sessions,setSessions]=useState<ProjectChatSession[]>([]),[session,setSession]=useState<ProjectChatSession|null>(null),[messages,setMessages]=useState<ProjectChatMessage[]>([]),[chatText,setChatText]=useState(""),[chatBusy,setChatBusy]=useState(false)
 const [request,setRequest]=useState("时序图3 流程图3 ER图1 数据流图3 类图1"),[plans,setPlans]=useState<DiagramPlan[]>([]),[activePlan,setActivePlan]=useState<DiagramPlan|null>(null),[diagrams,setDiagrams]=useState<ProjectDiagram[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("")
 async function refresh(){const [a,b,c,d]=await Promise.all([fetch(`/api/projects/${p.id}`).then(r=>r.json()),fetch(`/api/projects/${p.id}/chats`).then(r=>r.json()),fetch(`/api/projects/${p.id}/plans`).then(r=>r.json()),fetch(`/api/projects/${p.id}/diagrams`).then(r=>r.json())]);setProject(a.project||null);setSummary(a.project?.summaryText||"");setSessions(b.sessions||[]);setPlans(c.plans||[]);setActivePlan((c.plans||[])[0]||null);setDiagrams(d.diagrams||[])}
 useEffect(()=>{refresh()},[p.id])
 async function saveSummary(){setBusy(true);const x=await fetch(`/api/projects/${p.id}/summary`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({summaryText:summary})}).then(r=>r.json());if(x.project){setProject(x.project);setSaved(true)}setBusy(false)}
 async function newSession(){const x=await fetch(`/api/projects/${p.id}/chats`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title:`项目讨论 ${sessions.length+1}`)}).then(r=>r.json());setSessions(v=>[x.session,...v]);setSession(x.session);setMessages([])}
 async function openSession(s:ProjectChatSession){setSession(s);setMessages((await fetch(`/api/project-chats/${s.id}/messages`).then(r=>r.json())).messages||[])}
 async function sendChat(){if(!chatText.trim()||!session)return;const text=chatText;setChatText("");setChatBusy(true);const x=await fetch(`/api/projects/${p.id}/chat`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sessionId:session.id,message:text})}).then(r=>r.json());await openSession(session);if(x.error)setError(x.error);setChatBusy(false)}
 async function makePlan(){setError("");const x=await fetch(`/api/projects/${p.id}/plans`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({requestText:request})}).then(r=>r.json());if(x.error)return setError(x.error);setActivePlan(x.plan);setPlans(v=>[x.plan,...v])}
 function patchItem(id:string,patch:Partial<DiagramPlanItem>){if(activePlan)setActivePlan({...activePlan,items:activePlan.items.map(x=>x.id===id?{...x,...patch}:x)})}
 async function savePlan(){if(!activePlan)return;const x=await fetch(`/api/project-plans/${activePlan.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({items:activePlan.items})}).then(r=>r.json());setActivePlan(x.plan)}
 async function generateAll(){if(!activePlan)return;setBusy(true);setError("");await savePlan();const latest=(await fetch(`/api/project-plans/${activePlan.id}`).then(r=>r.json())).plan as DiagramPlan;await fetch(`/api/project-plans/${latest.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:"generating"})});let cursor=0;async function worker(){while(cursor<latest.items.length){const item=latest.items[cursor++];const x=await fetch(`/api/projects/${p.id}/generate`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({taskId:item.id})}).then(r=>r.json());if(x.error)setError(e=>e?e+"\n"+x.error:x.error)}}await Promise.all([worker(),worker()]);await fetch(`/api/project-plans/${latest.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:"completed"})});setBusy(false);await refresh();setTab("diagrams")}
 if(!project)return <main className="p-10">加载项目...</main>
 const nav=[["summary",FileText,"项目总结"],["chat",MessageSquare,"聊天记录"],["plan",Sparkles,"制图计划"],["diagrams",Images,`图表库 (${diagrams.length})`]] as const
 return <main className="min-h-screen bg-background p-4 md:p-6"><div className="mx-auto max-w-7xl space-y-4">
  <header className="flex items-center gap-3"><Button variant="ghost" size="icon" onClick={()=>router.push(`/${p.lang}/projects`)}><ArrowLeft/></Button><div className="flex-1"><h1 className="text-2xl font-semibold">{project.name}</h1><p className="text-sm text-muted-foreground">{project.code||"未设置项目编号"}</p></div><Button variant="outline" onClick={()=>router.push(`/${p.lang}`)}>自由绘图</Button></header>
  {error&&<pre className="whitespace-pre-wrap rounded-lg border border-destructive/40 p-3 text-sm text-destructive">{error}</pre>}
  <div className="grid gap-4 lg:grid-cols-[210px_1fr]"><aside className="rounded-xl border bg-card p-2">{nav.map(([k,I,t])=><button key={k} onClick={()=>setTab(k)} className={`mb-1 flex w-full items-center gap-2 rounded-md px-3 py-2 text-left text-sm ${tab===k?"bg-accent font-medium":"hover:bg-accent/60"}`}><I className="size-4"/>{t}</button>)}</aside>
  <section className="min-h-[650px] rounded-xl border bg-card p-5">
   {tab==="summary"&&<div className="space-y-4"><div><h2 className="text-lg font-semibold">项目总结</h2><p className="text-sm text-muted-foreground">项目模式所有 AI 分析和制图均以这份总结为事实来源。</p></div><ProjectSummaryTools projectId={p.id} onImported={t=>{setSummary(t);setSaved(true)}}/><textarea value={summary} onChange={e=>{setSummary(e.target.value);setSaved(false)}} className="min-h-[500px] w-full rounded-lg border bg-background p-4 font-mono text-sm leading-6" placeholder="粘贴其他 AI 生成的项目总结..."/><div className="flex justify-end gap-3">{saved&&<span className="self-center text-sm text-muted-foreground">已保存</span>}<Button onClick={saveSummary} disabled={busy}><Save/>保存总结</Button></div></div>}
   {tab==="chat"&&<div className="grid h-[610px] gap-4 md:grid-cols-[220px_1fr]"><div className="border-r pr-3"><Button className="w-full" onClick={newSession}><Plus/>新建对话</Button><div className="mt-3 space-y-1">{sessions.map(s=><button key={s.id} onClick={()=>openSession(s)} className="w-full rounded px-3 py-2 text-left text-sm hover:bg-accent">{s.title}</button>)}</div></div><div className="flex min-h-0 flex-col">{session?<><div className="flex-1 overflow-auto space-y-3">{messages.map(m=><div key={m.id} className={`rounded-lg p-3 text-sm whitespace-pre-wrap ${m.role==="user"?"ml-12 bg-primary text-primary-foreground":"mr-12 bg-muted"}`}>{m.content}</div>)}</div><div className="mt-3 flex gap-2"><textarea value={chatText} onChange={e=>setChatText(e.target.value)} className="min-h-20 flex-1 rounded border bg-background p-3" placeholder="根据项目总结提问..."/><Button onClick={sendChat} disabled={chatBusy}>{chatBusy?"回答中...":"发送"}</Button></div></>:<div className="m-auto text-muted-foreground">新建或选择一个项目对话</div>}</div></div>}
   {tab==="plan"&&<div className="space-y-4"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">制图计划</h2><select value={activePlan?.id||""} onChange={e=>setActivePlan(plans.find(x=>x.id===e.target.value)||null)} className="rounded border bg-background px-2 py-1 text-sm"><option value="">历史计划</option>{plans.map(x=><option key={x.id} value={x.id}>{new Date(x.createdAt).toLocaleString()} · {x.items.length}张</option>)}</select></div><div className="flex gap-2"><input value={request} onChange={e=>setRequest(e.target.value)} className="h-10 flex-1 rounded border bg-background px-3"/><Button onClick={makePlan}><Sparkles/>生成计划</Button></div>{activePlan&&<><div className="space-y-2">{activePlan.items.map((x)=><div key={x.id} className="grid gap-2 rounded-lg border p-3 md:grid-cols-[110px_1fr_1.4fr_auto]"><select value={x.type} onChange={e=>patchItem(x.id,{type:e.target.value as any})} className="rounded border bg-background px-2"><option value="sequence">时序图</option><option value="flowchart">流程图</option><option value="erd">ERD</option><option value="dfd">数据流图</option><option value="class">类图</option></select><input value={x.title} onChange={e=>patchItem(x.id,{title:e.target.value})} className="rounded border bg-background px-2"/><input value={x.description||""} onChange={e=>patchItem(x.id,{description:e.target.value})} className="rounded border bg-background px-2" placeholder="图表说明"/><Button variant="ghost" size="icon" onClick={()=>setActivePlan({...activePlan,items:activePlan.items.filter(y=>y.id!==x.id)})}><Trash2/></Button></div>)}</div><div className="flex justify-between gap-2"><Button variant="outline" onClick={()=>setActivePlan({...activePlan,items:[...activePlan.items,{id:crypto.randomUUID(),type:"flowchart",title:"新图表",description:"",order:activePlan.items.length,status:"pending"}]})}><Plus/>新增图表</Button><div className="flex gap-2"><Button variant="outline" onClick={savePlan}>保存计划</Button><Button onClick={generateAll} disabled={busy||!activePlan.items.length}>{busy?"批量生成中...":"确认并生成全部"}</Button></div></div></>}</div>}
   {tab==="diagrams"&&<div className="space-y-4"><h2 className="text-lg font-semibold">图表库</h2>{!diagrams.length?<div className="rounded-lg border border-dashed p-12 text-center text-muted-foreground">还没有图表，请先创建制图计划并生成。</div>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{diagrams.map(d=><button key={d.id} onClick={()=>router.push(`/${p.lang}/projects/${p.id}/diagrams/${d.id}`)} className="rounded-xl border p-4 text-left hover:bg-accent"><div className="mb-8 text-xs uppercase text-muted-foreground">{d.type}</div><div className="font-medium">{d.name}</div><div className="mt-1 text-xs text-muted-foreground">v{d.currentVersion} · {new Date(d.updatedAt).toLocaleString()}</div></button>)}</div>}</div>}
  </section></div>
 </div></main>
}